server:
    rootPath: /api/
    applicationConnectors:
      - type: http
        port: 8090
    adminConnectors:
      - type: http
        port: 8091

logging:
  level: INFO
  loggers:
    com.dccarlos.learning: DEBUG